### PR TITLE
Database

### PR DESCRIPTION
**Pull request by alechewitt**
Working with sharing and getting.
todo: 
- Handle dynamic loading of language properly. In order to allow us to have many more languages
- Handle errors correctly.
- Refactor some code to seperate out some of the logic with the DOM handling.
- Look at loading to prevent flash before snippet loaded

### CODE REVIEW

**Comment by Daio-io** [comment]
I have put the MongoDatabase implementation behind an interface (Repository) now so it can be swapped out if we ever wanted to change db. I have a few little bits to hook up before I am ready to merge. Mainly just making the service some kind of singleton, which will wrap up creating and injecting the Repository interface (MongoDatabase). 

After that I think we should merge and create some new branches to continue working on other features and the todo's you have outlined above

:smile:

**Comment by alechewitt** [comment]
Nice, yes sounds good to me. 
Let me know when you've done those few bits, then yes I agree we should merge into master and start creating new branches to do other other stuff.

**Comment by Daio-io** [comment]
:+1: I am happy to merge in. There is still some work to be done for project organisation and code tidy up etc but we should start breaking up the features now. Have a test and feel free to merge when you're ready

**Comment by alechewitt** [comment]
Just merged in. There was a small bug with saving the, language and snippet the wrong way round.
In other news, had some thoughts about a name. Will send you a google doc.

**Pull request merged**
